// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
#nullable enable
namespace BurgerBabyApi.Models.ViewModel
{
    public partial class ImgDeleteVM
    {
        [Required]
        public int ProductId { get; set; }
        public IFormFile? FormFile { get; set; }

    }
}

