// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBabyApi.Models.EFModel;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
#nullable enable
namespace BurgerBabyApi.Models.ViewModel
{
    public partial class ImgEditVM
    {
        [Required]
        public int Id { get; set; }
        public string? ImgName { get; set; } 
        public string? SaveName { get; set; } 
        [Required]
        public int ProductId { get; set; }
        public bool? IsCover { get; set; }
        public IFormFile? FormFile { get; set; }

    }
    public static class ImgEditVMExts {
        public static Img ToEntity(this ImgEditVM imgEditVM)
        {
            return new Img
            {
                Id = imgEditVM.Id,
                ImgName = imgEditVM.ImgName,
                SaveName = imgEditVM.SaveName,
                ProductId = imgEditVM.ProductId,
                IsCover=imgEditVM.IsCover,
            };
        }
        public static ImgEditVM ToEditVM(this Img img)
        {
            return new ImgEditVM
            {
                Id = img.Id,
                ImgName = img.ImgName,
                SaveName = img.SaveName,
                ProductId = img.ProductId,
                IsCover = img.IsCover,
            };
        }
    }
}

