// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBabyApi.Models;
using System;
using System.Collections.Generic;

namespace BurgerBabyApi.Models.EFModel;

public partial class MemberDTO
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }
    public virtual Role Role { get; set; }


}
public static class MemberVMExt
{
    public static MemberDTO ToDto(this Member member)
    {
        return new MemberDTO
        {
            Id = member.Id,
            Name = member.Name,
            Phone = member.Phone,
            Address = member.Address,
            Email = member.Email,
            Password = member.Password,
            RoleId = member.RoleId,
            Role = member.Role,

        };
    }

    public static Member ToEntity(this MemberDTO memberDTO)
    {
        return new Member
        {
            Id = memberDTO.Id,
            Name = memberDTO.Name,
            Phone = memberDTO.Phone,
            Address = memberDTO.Address,
            Email = memberDTO.Email,
            Password = memberDTO.Password,
            RoleId = memberDTO.RoleId,
            Role = memberDTO.Role,

        };
    }

}