// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BurgerBabyApi.Models.EFModel
{
    public partial class Img
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ImgName { get; set; }
        public string SaveName { get; set; }
        public bool? IsCover { get; set; }

        public virtual Product Product { get; set; }
    }
}