// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BurgerBaby.Models.EFModel;

public partial class ProductDTO
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<Img> Imgs { get; set; }

    public string Intro { get; set; }=string.Empty;


}
public static class ProductExt
{
    public static Product ToEntity(this ProductDTO productDTO)
    {
        return new Product
        {
            Id = productDTO.Id,

            Name = productDTO.Name,
            Price = productDTO.Price,

            Imgs=productDTO.Imgs,
            Intro = productDTO.Intro
        };
    }
    public static ProductDTO ToDto(this Product product)
    {
        return new ProductDTO
        {
            Id = product.Id,

            Name = product.Name,
            Price = product.Price,

            Imgs = product.Imgs,
            Intro = product.Intro
        };
    }
}