// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using BurgerBabyApi.Models.EFModel;

namespace BurgerBabyApi.Models.ViewModel;

public partial class RoleCreateVM
{
    public int Id { get; set; }
    [Display(Name = "規則")]
    [Required]
    public string RoleName { get; set; }
    public virtual ICollection<Member> Members { get; set; }

}
public static partial class RoleCreateVMExt
{
    public static Role ToEntity(this RoleCreateVM roleCreateVM)
    {

        return new Role
        {
            Id = roleCreateVM.Id,
            RoleName = roleCreateVM.RoleName,
            Members = roleCreateVM.Members,
        };
    }
    public static RoleCreateVM ToCreateVM(this Role role)
    {
        return new RoleCreateVM
        {
            Id = role.Id,
            RoleName = role.RoleName,
            Members = role.Members,
        };
    }
}