// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBabyApi.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BurgerBabyApi.Models.ViewModel;

public partial class RoleEditVM
{
    public int Id { get; set; }
    [Display(Name = "規則")]
    public string RoleName { get; set; }

    public virtual ICollection<Member> Members { get; set; }
}
public static partial class RoleEditVMExt
{
    public static Role ToEntity(this RoleEditVM roleEditVM)
    {

        return new Role
        {
            Id = roleEditVM.Id,
            RoleName = roleEditVM.RoleName,
            Members = roleEditVM.Members,
        };
    }
    public static RoleEditVM ToEditVM(this Role role)
    {
        return new RoleEditVM
        {
            Id = role.Id,
            RoleName = role.RoleName,
            Members = role.Members,
        };
    }
}