// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using BurgerBaby.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BurgerBaby.Models.ViewModel;

public partial class ProductCreateVM
{
    public int Id { get; set; }
    [Display(Name = "商品名")]
    public string Name { get; set; }

    [Display(Name = "價格")]
    public decimal Price { get; set; }

    [Display(Name = "圖片")]
    public virtual ICollection<Img> Imgs { get; set; }

    [Display(Name = "產品資訊")]
    [MaxLength(1000,ErrorMessage ="不能多於1000")]
    public string Intro { get; set; }

}
public static partial class ProductCreateVMExt
{
    public static Product ToEntity(this ProductCreateVM productCreateVM)
    {

        return new Product
        {
            Id = productCreateVM.Id,
            Name = productCreateVM.Name,

            Price = productCreateVM.Price,

            Imgs = productCreateVM.Imgs,
            Intro = productCreateVM.Intro
        };
    }
    public static ProductCreateVM ToCreateVM(this Product product)
    {
        return new ProductCreateVM
        {
            Id = product.Id,
            Name = product.Name,

            Price = product.Price,

            Imgs = product.Imgs,
            Intro = product.Intro
        };
    }
}