// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBaby.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;


namespace BurgerBaby.Models.ViewModel;

public partial class ProductEditVM
{
    public int Id { get; set; }
    [Display(Name = "商品名")]
    public string Name { get; set; }

    [Display(Name = "價格")]
    public decimal Price { get; set; }
   

    [Display(Name = "圖片")]
    public virtual ICollection<Img> Imgs { get; set; }

    [Display(Name = "產品資訊")]
    [MaxLength(1000, ErrorMessage = "不能多於1000")]
    public string Intro { get; set; }

}

public static partial class ProductEditVMExt
{
    public static Product ToEntity(this ProductEditVM productEditVM)
    {

        return new Product
        {
            Id = productEditVM.Id,
            Name = productEditVM.Name,

            Price = productEditVM.Price,

            Imgs = productEditVM.Imgs,
            Intro = productEditVM.Intro
        };
    }
    public static ProductEditVM ToEditVM(this Product product)
    {
        return new ProductEditVM
        {
            Id = product.Id,
            Name = product.Name,

            Price = product.Price,

            Imgs = product.Imgs,
            Intro = product.Intro
        };
    }
}