// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBaby.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;


namespace BurgerBaby.Models.ViewModel;

public partial class ProductDeleteVM
{
    public int Id { get; set; }
    [Display(Name = "商品名")]
    public string Name { get; set; }

    [Display(Name = "價格")]
    public decimal Price { get; set; }

    [Display(Name = "圖片")]
    public virtual ICollection<Img> Imgs { get; set; }
#nullable enable
    [Display(Name = "產品資訊")]
    public string? Intro { get; set; }
#nullable disable
}

public static partial class ProductDeleteVMExt
{
    public static Product ToEntity(this ProductDeleteVM productDeleteVM)
    {

        return new Product
        {
            Id = productDeleteVM.Id,
            Name = productDeleteVM.Name,

            Price = productDeleteVM.Price,

            Imgs = productDeleteVM.Imgs,
            Intro = productDeleteVM.Intro
        };
    }
    public static ProductDeleteVM ToDeleteVM(this Product product)
    {
        return new ProductDeleteVM
        {
            Id = product.Id,
            Name = product.Name,

            Price = product.Price,

            Imgs = product.Imgs,
            Intro = product.Intro
        };
    }
}