// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBabyApi.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

//todo 將VM裡所有預設關聯副TABLE子TABLE的更改調並修改程式
namespace BurgerBabyApi.Models.ViewModel;

public partial class ProductVM
{
    public int Id { get; set; }
    [Display(Name = "商品名")]
    public string Name { get; set; }

    [Display(Name = "價格")]
    public decimal Price { get; set; }

    [Display(Name = "圖片")]
    public virtual ICollection<Img> Imgs { get; set; }
#nullable enable
    [Display(Name = "產品資訊")]
    public string? Intro { get; set; }
#nullable disable
}
public static partial  class ProductVMExt {
    public static Product ToEntity(this ProductVM productVM)
    {
        
        return new Product { 
        Id = productVM.Id,
        Name = productVM.Name,

        Price = productVM.Price,

        Imgs=productVM.Imgs,
            Intro = productVM.Intro
        };
    }
    public static ProductVM ToVM(this Product product)
    {
        return new ProductVM
        {
            Id = product.Id,
            Name = product.Name,

            Price = product.Price,

            Imgs = product.Imgs,
            Intro = product.Intro
        };
    }
}