// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using BurgerBaby.Models.EFModel;

namespace BurgerBaby.Models.ViewModel;

public partial class RoleDeleteVM
{
    public int Id { get; set; }
    [Display(Name = "規則")]
    public string RoleName { get; set; }
    public virtual ICollection<Member> Members { get; set; }

}
public static partial class RoleDeleteVMExt
{
    public static Role ToEntity(this RoleDeleteVM roleDeleteVM)
    {

        return new Role
        {
            Id = roleDeleteVM.Id,
            RoleName = roleDeleteVM.RoleName,
            Members = roleDeleteVM.Members,
        };
    }
    public static RoleDeleteVM ToDeleteVM(this Role role)
    {
        return new RoleDeleteVM
        {
            Id = role.Id,
            RoleName = role.RoleName,
            Members = role.Members,
        };
    }
}