// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBaby.Models.EFModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BurgerBaby.Models.ViewModel;

public partial class RoleVM
{
    public int Id { get; set; }
    [Display(Name = "規則")]
    public string RoleName { get; set; }
    public virtual ICollection<Member> Members { get; set; }
}
public static partial class RoleVMExt
{
    public static Role ToEntity(this RoleVM roleVM)
    {

        return new Role
        {
            Id = roleVM.Id,
           RoleName = roleVM.RoleName,
           Members = roleVM.Members,
        };
    }
    public static RoleVM ToVM(this Role role)
    {
        return new RoleVM
        {
            Id = role.Id,
            RoleName = role.RoleName,
            Members = role.Members,
        };
    }
}