// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BurgerBaby.Models.EFModel
{
    public partial class Product
    {
        public Product()
        {
            Imgs = new HashSet<Img>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Intro { get; set; }

        public virtual ICollection<Img> Imgs { get; set; }
    }
}