// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BurgerBaby.Models.EFModel
{
    public partial class Role
    {
        public Role()
        {
            Members = new HashSet<Member>();
        }

        public int Id { get; set; }
        public string RoleName { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}