// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BurgerBaby.Models.EFModel;
using System;
using System.Collections.Generic;

namespace BurgerBaby.Models.ViewModel;

public partial class ImgVM
{
    public int Id { get; set; }

    public string ImgName { get; set; }

    public string SaveName { get; set; }

    public bool? IsCover { get; set; }
    public int ProductId { get; set; }

    public Product Product { get; set; }
}